export const NEIGHBORHOODS = [
  {
    id: "fallback-almaty-medeu",
    citySlug: "almaty",
    cityName: "Алматы",
    name: "Медеуский",
    description: "Премиальный район у подножия гор. Чистый воздух и красивые виды.",
    priceLabel: "От 180 000 ₸",
    trendLabel: "+8%",
    imageUrl: "https://images.unsplash.com/photo-1549893077-a3caa2f9b6c3?auto=format&fit=crop&w=800&q=60",
    tags: ["Горы", "Тишина", "Экология"],
  },
  {
    id: "fallback-almaty-bostandyk",
    citySlug: "almaty",
    cityName: "Алматы",
    name: "Бостандыкский",
    description: "Много университетов, кафе, доступно для студентов.",
    priceLabel: "От 90 000 ₸",
    trendLabel: "+5%",
    imageUrl: "https://images.unsplash.com/photo-1519121785383-3229633bb75b?auto=format&fit=crop&w=800&q=60",
    tags: ["Студенты", "Кафе", "Метро"],
  },
  {
    id: "fallback-almaty-almaly",
    citySlug: "almaty",
    cityName: "Алматы",
    name: "Алмалинский",
    description: "Центр города, пешком до работы в офисах и бизнес-центрах.",
    priceLabel: "От 150 000 ₸",
    trendLabel: "+6%",
    imageUrl: "https://images.unsplash.com/photo-1519642918688-7e43b19245d8?auto=format&fit=crop&w=800&q=60",
    tags: ["Центр", "Работа", "Метро"],
  },
  {
    id: "fallback-astana-esil",
    citySlug: "astana",
    cityName: "Астана",
    name: "Есильский",
    description: "Современные ЖК, небоскрёбы, деловой центр столицы.",
    priceLabel: "От 140 000 ₸",
    trendLabel: "+10%",
    imageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=800&q=60",
    tags: ["Новостройки", "Деловой"],
  },
  {
    id: "fallback-astana-saryarka",
    citySlug: "astana",
    cityName: "Астана",
    name: "Сарыаркинский",
    description: "Спокойный район рядом с парками и торговыми центрами.",
    priceLabel: "От 95 000 ₸",
    trendLabel: "+3%",
    imageUrl: "https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&w=800&q=60",
    tags: ["Парки", "Семьи"],
  },
  {
    id: "fallback-shymkent-al-farabi",
    citySlug: "shymkent",
    cityName: "Шымкент",
    name: "Аль-Фарабийский",
    description: "Центр Шымкента, активная жизнь, рынки и магазины.",
    priceLabel: "От 70 000 ₸",
    trendLabel: "+4%",
    imageUrl: "https://images.unsplash.com/photo-1528901166007-3784c7dd3653?auto=format&fit=crop&w=800&q=60",
    tags: ["Центр", "Магазины"],
  },
];
